# Definition for CI within GitLab
# Note:
#    Prefix any job name with a '.' to disable.
#


# Enable submodules
variables:
  GIT_STRATEGY: clone
  GIT_SUBMODULE_STRATEGY: none


#### Builds ####
.build-base: &build_base
  stage: build
  script:
    - git submodule sync ci
    - git submodule update --init ci
    - ci/build.sh native install
  artifacts:
    when: always
    paths:
      - artifacts/
      - ci-logs/
    reports:
      junit:
        # The Tests for cc generates a JunitXML output file.
        - artifacts/results.xml

build-linux:
  <<: *build_base
  tags:
    - linux

build-macos:
  <<: *build_base
  tags:
    - macos


#### Stages to execute ####
stages:
#  - export
  - build
